# Generated by Django 5.0.4 on 2025-10-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('full_case_study', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('WEB', 'Web Development'), ('SOFT', 'Software Solution'), ('CONS', 'Consulting')], max_length=5)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('website_url', models.URLField(blank=True, verbose_name='Project URL')),
                ('github_url', models.URLField(blank=True)),
                ('technologies_used', models.CharField(help_text='Comma-separated list', max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('completion_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
