# Generated by Django 5.0.4 on 2025-10-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('short_description', models.TextField(max_length=200)),
                ('detailed_description', models.TextField()),
                ('icon_class', models.CharField(blank=True, help_text="e.g., 'fas fa-code' for FontAwesome", max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='services/')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
